//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyskTech.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt_local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RyskTech.Resources.Language.pt_local", typeof(pt_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações Adicionais.
        /// </summary>
        internal static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        internal static string AddressComplement {
            get {
                return ResourceManager.GetString("AddressComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        internal static string AddressZIP {
            get {
                return ResourceManager.GetString("AddressZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente.
        /// </summary>
        internal static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vidro temperado âmbar.
        /// </summary>
        internal static string AmberGlassContainer {
            get {
                return ResourceManager.GetString("AmberGlassContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risco Associado.
        /// </summary>
        internal static string AssociatedRisk {
            get {
                return ResourceManager.GetString("AssociatedRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avenida.
        /// </summary>
        internal static string Avenue {
            get {
                return ResourceManager.GetString("Avenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alameda.
        /// </summary>
        internal static string Boulevard {
            get {
                return ResourceManager.GetString("Boulevard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prédio.
        /// </summary>
        internal static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número CAS.
        /// </summary>
        internal static string CasNumber {
            get {
                return ResourceManager.GetString("CasNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipiente.
        /// </summary>
        internal static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travessa.
        /// </summary>
        internal static string Crossing {
            get {
                return ResourceManager.GetString("Crossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perigo.
        /// </summary>
        internal static string Danger {
            get {
                return ResourceManager.GetString("Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Características de periculosidade.
        /// </summary>
        internal static string DangerCharacteristics {
            get {
                return ResourceManager.GetString("DangerCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dias.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diretor.
        /// </summary>
        internal static string Director {
            get {
                return ResourceManager.GetString("Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        internal static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de e-mail.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máquina/Equipamento.
        /// </summary>
        internal static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor informe o nome ou descritor do seu espaço.
        /// </summary>
        internal static string ErrorInvalidLabName {
            get {
                return ResourceManager.GetString("ErrorInvalidLabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de unidade inválido!.
        /// </summary>
        internal static string ErrorInvalidUnitName {
            get {
                return ResourceManager.GetString("ErrorInvalidUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique o nome do agente.
        /// </summary>
        internal static string ErrorNoAgentName {
            get {
                return ResourceManager.GetString("ErrorNoAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique a origem de todos os agentes químicos.
        /// </summary>
        internal static string ErrorNoAgentOrigin {
            get {
                return ResourceManager.GetString("ErrorNoAgentOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique os usos do seu agente.
        /// </summary>
        internal static string ErrorNoAgentUsage {
            get {
                return ResourceManager.GetString("ErrorNoAgentUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor insira o perigo associado a todos os riscos.
        /// </summary>
        internal static string ErrorNoAssociatedDanger {
            get {
                return ResourceManager.GetString("ErrorNoAssociatedDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique os agentes biológicos presentes em seu laboratório.
        /// </summary>
        internal static string ErrorNoBiologicalAgents {
            get {
                return ResourceManager.GetString("ErrorNoBiologicalAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor complete as considerações gerais sobre os resultados da análise.
        /// </summary>
        internal static string ErrorNoConclusion {
            get {
                return ResourceManager.GetString("ErrorNoConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor preencha com suas informações de concordância FISPQ.
        /// </summary>
        internal static string ErrorNoFISPQExplanation {
            get {
                return ResourceManager.GetString("ErrorNoFISPQExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique a classe de frequência de todos os riscos.
        /// </summary>
        internal static string ErrorNoFrequencyClassificaiton {
            get {
                return ResourceManager.GetString("ErrorNoFrequencyClassificaiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione pelo menos um tipo de material manipulado na sua unidade!.
        /// </summary>
        internal static string ErrorNoManipulatedAreasSelected {
            get {
                return ResourceManager.GetString("ErrorNoManipulatedAreasSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique a ocupação de todos os resposáveis.
        /// </summary>
        internal static string ErrorNoOccupation {
            get {
                return ResourceManager.GetString("ErrorNoOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor cite todos os agentes físicos e seus riscos associados.
        /// </summary>
        internal static string ErrorNoPhyisicalAgents {
            get {
                return ResourceManager.GetString("ErrorNoPhyisicalAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique todas as amostras biológicasprocessadas pelo seu laboratório.
        /// </summary>
        internal static string ErrorNoProcessedSamples {
            get {
                return ResourceManager.GetString("ErrorNoProcessedSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique o destino dos resíduos.
        /// </summary>
        internal static string ErrorNoResidueDestination {
            get {
                return ResourceManager.GetString("ErrorNoResidueDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor descreva de maneira geral como são mantidos os resíduos.
        /// </summary>
        internal static string ErrorNoResidueStorageDescription {
            get {
                return ResourceManager.GetString("ErrorNoResidueStorageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique a classe de risco do agente.
        /// </summary>
        internal static string ErrorNoRiskClassificaiton {
            get {
                return ResourceManager.GetString("ErrorNoRiskClassificaiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor descreva todos os riscos listados.
        /// </summary>
        internal static string ErrorNoRiskDescription {
            get {
                return ResourceManager.GetString("ErrorNoRiskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique os riscos presentes no seu laboratório.
        /// </summary>
        internal static string ErrorNoRisks {
            get {
                return ResourceManager.GetString("ErrorNoRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique a classe de severidade de todos os riscos.
        /// </summary>
        internal static string ErrorNoSeverityClassification {
            get {
                return ResourceManager.GetString("ErrorNoSeverityClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor sugira formas de melhorar a segurança no seu ambiente.
        /// </summary>
        internal static string ErrorNoSugestions {
            get {
                return ResourceManager.GetString("ErrorNoSugestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique a composição do time.
        /// </summary>
        internal static string ErrorNoTeamComposition {
            get {
                return ResourceManager.GetString("ErrorNoTeamComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor descreva o uso do seu espaço.
        /// </summary>
        internal static string ErrorNoUsageDescription {
            get {
                return ResourceManager.GetString("ErrorNoUsageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andar.
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação de Frequência.
        /// </summary>
        internal static string FrequencyClassification {
            get {
                return ResourceManager.GetString("FrequencyClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodovia.
        /// </summary>
        internal static string Highway {
            get {
                return ResourceManager.GetString("Highway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor informe a quantidade de cada integrante do time.
        /// </summary>
        internal static string IncompleteTeamCounter {
            get {
                return ResourceManager.GetString("IncompleteTeamCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inerte.
        /// </summary>
        internal static string Inert {
            get {
                return ResourceManager.GetString("Inert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique os detalhes de contenção do agente.
        /// </summary>
        internal static string InvalidAgentContainer {
            get {
                return ResourceManager.GetString("InvalidAgentContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique a unidade de medida utilizada.
        /// </summary>
        internal static string InvalidAgentMeasureUnit {
            get {
                return ResourceManager.GetString("InvalidAgentMeasureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor digite o nome do agente.
        /// </summary>
        internal static string InvalidAgentName {
            get {
                return ResourceManager.GetString("InvalidAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique a quantidade mantida do agente.
        /// </summary>
        internal static string InvalidAgentQuantity {
            get {
                return ResourceManager.GetString("InvalidAgentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor digite um endereço de e-mail válido.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor digite um nome válido.
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor digite um número de telefone válido.
        /// </summary>
        internal static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique o estado físico do agente.
        /// </summary>
        internal static string InvalidPhysicalState {
            get {
                return ResourceManager.GetString("InvalidPhysicalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique o prédio para todos os espaços da sua unidade.
        /// </summary>
        internal static string InvalidSpaceBuilding {
            get {
                return ResourceManager.GetString("InvalidSpaceBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique o andar para todos os espaços da sua unidade.
        /// </summary>
        internal static string InvalidSpaceFloor {
            get {
                return ResourceManager.GetString("InvalidSpaceFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique a sala para todos os espaços da sua unidade.
        /// </summary>
        internal static string InvalidSpaceRoom {
            get {
                return ResourceManager.GetString("InvalidSpaceRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique horários no formato HH:MM em notação 24h.
        /// </summary>
        internal static string InvalidTimeFormat {
            get {
                return ResourceManager.GetString("InvalidTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique os horários de início e fim de todos os espaços da sua unidade.
        /// </summary>
        internal static string InvalidUsageTurn {
            get {
                return ResourceManager.GetString("InvalidUsageTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor digite um bairro válido para sua unidade!.
        /// </summary>
        internal static string LocationDistrictInvalid {
            get {
                return ResourceManager.GetString("LocationDistrictInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor digite um número válido para sua unidade!.
        /// </summary>
        internal static string LocationNumberInvalid {
            get {
                return ResourceManager.GetString("LocationNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um prefixo para o endereço da sua unidade!.
        /// </summary>
        internal static string LocationPrefixInvalid {
            get {
                return ResourceManager.GetString("LocationPrefixInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor digite o nome do logradouro da sua unidade!.
        /// </summary>
        internal static string LocationStreetInvalid {
            get {
                return ResourceManager.GetString("LocationStreetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor digite o CEP no formato correto!.
        /// </summary>
        internal static string LocationZIPInvalid {
            get {
                return ResourceManager.GetString("LocationZIPInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mistura.
        /// </summary>
        internal static string Mixture {
            get {
                return ResourceManager.GetString("Mixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro..
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor preencha o formulário com o histórico da sua unidade.
        /// </summary>
        internal static string NoHistory {
            get {
                return ResourceManager.GetString("NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor insira os espaços utilizados pela sua unidade.
        /// </summary>
        internal static string NoSpacesAdded {
            get {
                return ResourceManager.GetString("NoSpacesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor insira informações sobre os arredores da sua unidade.
        /// </summary>
        internal static string NoSurroundingsDetailsAdded {
            get {
                return ResourceManager.GetString("NoSurroundingsDetailsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor preencha todas as abas antes de completar o documento!.
        /// </summary>
        internal static string NotAllTabsVisited {
            get {
                return ResourceManager.GetString("NotAllTabsVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor indique os dias em que o espaço é utilizado.
        /// </summary>
        internal static string NoUsageDays {
            get {
                return ResourceManager.GetString("NoUsageDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem.
        /// </summary>
        internal static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor especifique o que são &quot;Outros&quot;.
        /// </summary>
        internal static string OtherNotSpecified {
            get {
                return ResourceManager.GetString("OtherNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado físico.
        /// </summary>
        internal static string PhysicalState {
            get {
                return ResourceManager.GetString("PhysicalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bombona plástica.
        /// </summary>
        internal static string PlasticContainer {
            get {
                return ResourceManager.GetString("PlasticContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Público.
        /// </summary>
        internal static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risco.
        /// </summary>
        internal static string Risk {
            get {
                return ResourceManager.GetString("Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classe de Risco.
        /// </summary>
        internal static string RiskClassification {
            get {
                return ResourceManager.GetString("RiskClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rua.
        /// </summary>
        internal static string Road {
            get {
                return ResourceManager.GetString("Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala.
        /// </summary>
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvaguarda.
        /// </summary>
        internal static string SafetyNet {
            get {
                return ResourceManager.GetString("SafetyNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação de severidade.
        /// </summary>
        internal static string SeverityClassification {
            get {
                return ResourceManager.GetString("SeverityClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações adicionais de armazenamento.
        /// </summary>
        internal static string StorageInfo {
            get {
                return ResourceManager.GetString("StorageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string StreetNumber {
            get {
                return ResourceManager.GetString("StreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alunos e Estudantes.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações sobre os arredores.
        /// </summary>
        internal static string SurroundingsComments {
            get {
                return ResourceManager.GetString("SurroundingsComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professores.
        /// </summary>
        internal static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profissionais Técnico-Administrativos.
        /// </summary>
        internal static string Technics {
            get {
                return ResourceManager.GetString("Technics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vidro temperado transparente.
        /// </summary>
        internal static string TemperedGlassContainer {
            get {
                return ResourceManager.GetString("TemperedGlassContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor informe a periodicidade com a qual seu laboratório treina seu pessoal.
        /// </summary>
        internal static string TrainingPeriodicityNotComplete {
            get {
                return ResourceManager.GetString("TrainingPeriodicityNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor especifique quem são aqueles envolvidos no seu treinamento.
        /// </summary>
        internal static string TrainingPersonelNotSpecified {
            get {
                return ResourceManager.GetString("TrainingPersonelNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Unidade - Histórico].
        /// </summary>
        internal static string UnitHistoryScreen {
            get {
                return ResourceManager.GetString("UnitHistoryScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Unidade - Localização].
        /// </summary>
        internal static string UnitLocationScreen {
            get {
                return ResourceManager.GetString("UnitLocationScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Unidade - Metodologia].
        /// </summary>
        internal static string UnitMethodologyScreen {
            get {
                return ResourceManager.GetString("UnitMethodologyScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Unidade - Estrutura].
        /// </summary>
        internal static string UnitStructureScreen {
            get {
                return ResourceManager.GetString("UnitStructureScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Unidade - Time].
        /// </summary>
        internal static string UnitTeamScreen {
            get {
                return ResourceManager.GetString("UnitTeamScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Unidade - Bem Vindo!].
        /// </summary>
        internal static string UnitWelcomeScreen {
            get {
                return ResourceManager.GetString("UnitWelcomeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período de Uso.
        /// </summary>
        internal static string UsagePeriod {
            get {
                return ResourceManager.GetString("UsagePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice-Diretor.
        /// </summary>
        internal static string ViceDirector {
            get {
                return ResourceManager.GetString("ViceDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
