//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyskTech.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RyskTech.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap biological {
            get {
                object obj = ResourceManager.GetObject("biological", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75-43-3	
        ///57-14-7 	
        ///106-99-0	
        ///78-93-3	
        ///141-78-6	
        ///79-20-9	
        ///123-86-4	
        ///105-46-4	
        ///67-64-1	
        ///74-90-8	
        ///7647-01-0	
        ///7664-39-3	
        ///7697-37-2	
        ///79-21-0	
        ///07783-07-5	
        ///07783-06-4	
        ///107-13-1	
        ///107-02-8	
        ///107-18-6	
        ///107-11-9	
        ///7664-41-7	
        ///7784-34-1	
        ///7726-95-6 	
        ///110-82-7	
        ///108-91-8	
        ///506-77-4	
        ///814-68-6	
        ///75-00-3	
        ///74-87-3	
        ///75-09-2	
        ///7782-50-5	
        ///108-23-6	
        ///79-22-1	
        ///109-61-5	
        ///67-66-3	
        ///542-88-1	
        ///107-30-2	
        ///123-73-9	
        ///98-82-8	
        ///19287-45-7	
        ///75-43-4	
        ///10049-04-4	
        ///07446-09-5	
        ///75-15-0	
        ///106-89-8	
        ///64-17-5	
        ///107 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cas_numbers {
            get {
                return ResourceManager.GetString("cas_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chemical {
            get {
                object obj = ResourceManager.GetObject("chemical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conclusion {
            get {
                object obj = ResourceManager.GetObject("conclusion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Na análise foram considerados os ricos provocados por agentes químicos, físicos e biológicos. Complementarmente, também foram identificados os riscos de acidente por agentes mecânicos.
        ///  
        ///	De acordo com a NR-9 do Ministério do Trabalho e Emprego (MTE, 1994), consideram-se agentes químicos substâncias, compostos ou produtos que possam penetrar no organismo pela via respiratória, nas formas de poeiras, fumo, névoas, neblinas, gases ou vapores, ou que pela natureza da atividade de exposição, possam ter cont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_methodology {
            get {
                return ResourceManager.GetString("default_methodology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap history {
            get {
                object obj = ResourceManager.GetObject("history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap location {
            get {
                object obj = ResourceManager.GetObject("location", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 750
        ///100
        ///250
        ///750
        ///750
        ///750
        ///1000
        ///1000
        ///750
        ///50
        ///50
        ///50
        ///100
        ///250
        ///50
        ///50
        ///100
        ///100
        ///250
        ///100
        ///100
        ///50
        ///100
        ///750
        ///250
        ///100
        ///100
        ///250
        ///100
        ///750
        ///50
        ///250
        ///100
        ///250
        ///250
        ///100
        ///100
        ///250
        ///1000
        ///50
        ///500
        ///50
        ///50
        ///250
        ///500
        ///1000
        ///750
        ///100
        ///500
        ///50
        ///50
        ///750
        ///50
        ///50
        ///50
        ///250
        ///250
        ///750
        ///50
        ///750
        ///500
        ///100
        ///1000
        ///250
        ///750
        ///250
        ///100
        ///750
        ///100
        ///250
        ///1000
        ///1000
        ///500
        ///500
        ///1000
        ///750
        ///50
        ///1000
        ///100
        ///250
        ///1000
        ///250
        ///50
        ///250
        ///250
        ///500
        ///250
        ///250
        ///100
        ///500
        ///50
        ///500
        ///250
        ///250
        ///50
        ///100
        ///50
        ///250
        ///250
        ///250
        ///250
        ///.
        /// </summary>
        internal static string massaReferencia {
            get {
                return ResourceManager.GetString("massaReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mechanical {
            get {
                object obj = ResourceManager.GetObject("mechanical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap methodolody {
            get {
                object obj = ResourceManager.GetObject("methodolody", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap physical {
            get {
                object obj = ResourceManager.GetObject("physical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Quadro1 {
            get {
                object obj = ResourceManager.GetObject("Quadro1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Quadro2 {
            get {
                object obj = ResourceManager.GetObject("Quadro2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Quadro3 {
            get {
                object obj = ResourceManager.GetObject("Quadro3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Quadro4 {
            get {
                object obj = ResourceManager.GetObject("Quadro4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap risk {
            get {
                object obj = ResourceManager.GetObject("risk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap safety {
            get {
                object obj = ResourceManager.GetObject("safety", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap structure {
            get {
                object obj = ResourceManager.GetObject("structure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1- dicloroetano	
        ///1,1- dimetilhidrazina	
        ///1,3- butadieno	
        ///2-butanona	
        ///Acetato de etila	
        ///Acetato de metila	
        ///Acetato de n-butila	
        ///Acetato de sec-butila	
        ///Acetona	
        ///Ácido cianídrico	
        ///Ácido clorídrico	
        ///Ácido fluorídrico	
        ///Ácido nítrico	
        ///Ácido peracético	
        ///Ácido selênico	
        ///Ácido sulfídrico	
        ///Acrilonitrila	
        ///Acroleína	
        ///Álcool alílico	
        ///Alilamina	
        ///Amônia	
        ///Arsina	
        ///Bromo	
        ///Ciclohexano	
        ///Ciclohexilamina	
        ///Cloreto cianogênico	
        ///Cloreto de acrila	
        ///Cloreto de etila	
        ///Cloreto de metila	
        ///Cloreto de metilen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string substances {
            get {
                return ResourceManager.GetString("substances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap team {
            get {
                object obj = ResourceManager.GetObject("team", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
